num1=int(input("enter number 1"))
num2=int(input("enter number 2"))
num3=int(input("enter number 3"))
if(num1>=num2 and num2<=num3):
    print("num1 is greater")
elif(num2>=num3 and num3<=num1):
    print("num2 is greater")
elif(num3>=num1 and num1<=num2):
    print("num3 is greater")